
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ComplainInterface extends javax.swing.JFrame {
    Connection conn;
   Statement statement;
   ResultSet resultSet,resultSetPass;
   ResultSetMetaData resultsetMetaData;
    String id;
    public ComplainInterface() {
        initComponents();
    }
    
    public ComplainInterface(String stu_id) {
        initComponents();
        OracleConnection OC=new OracleConnection();
        String[] stringArray = OC.connection();
        try{
            conn=DriverManager.getConnection(stringArray[0],stringArray[1],stringArray[2]);
            if(conn!=null)
            {
                
                System.out.println("Connection Sucessful in Complain_Interface");
                //statement=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);             
            }    
        }catch(SQLException e){
            System.out.println("Connection failed");
        }
        //resultSetPass=res;
        id=stu_id;
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE );
        seatcancelbtn.setActionCommand("Seat Cancel");
        cleanbtn.setActionCommand("Clean Issue");
        foodbtn.setActionCommand("Food Issue");
        electricitybtn.setActionCommand("Electricity Issue");
        internetbtn.setActionCommand("Internet Issue");
        laundybtn.setActionCommand("Laundry Issue");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IssueBtnGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seatcancelbtn = new javax.swing.JRadioButton();
        cleanbtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        decriptionArea = new javax.swing.JTextArea();
        foodbtn = new javax.swing.JRadioButton();
        electricitybtn = new javax.swing.JRadioButton();
        internetbtn = new javax.swing.JRadioButton();
        laundybtn = new javax.swing.JRadioButton();
        submitBtnLabel = new javax.swing.JLabel();
        crossBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(518, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(518, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(24, 44, 97));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Issue Type");

        IssueBtnGrp.add(seatcancelbtn);
        seatcancelbtn.setText("Seat Cancellation");

        IssueBtnGrp.add(cleanbtn);
        cleanbtn.setText("Clean Issue");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Issue Description");

        decriptionArea.setColumns(20);
        decriptionArea.setRows(5);
        jScrollPane1.setViewportView(decriptionArea);

        IssueBtnGrp.add(foodbtn);
        foodbtn.setText("Food Issue");

        IssueBtnGrp.add(electricitybtn);
        electricitybtn.setText("Electricity Issue");

        IssueBtnGrp.add(internetbtn);
        internetbtn.setText("Internet Issue");

        IssueBtnGrp.add(laundybtn);
        laundybtn.setText("Laundry Issue");

        submitBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SubmitApplication.png"))); // NOI18N
        submitBtnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnLabelMouseClicked(evt);
            }
        });

        crossBtnLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        crossBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        crossBtnLabel.setText("X");
        crossBtnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crossBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossBtnLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(submitBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seatcancelbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(foodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(internetbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laundybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cleanbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(electricitybtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(crossBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(crossBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatcancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodbtn)
                    .addComponent(electricitybtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetbtn)
                    .addComponent(laundybtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnLabelMouseClicked
         String issusename=IssueBtnGrp.getSelection().getActionCommand();
        System.out.println(issusename);
        String description=decriptionArea.getText();
        int response = JOptionPane.showConfirmDialog(null, "Are you Confirm?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            //System.out.println("No button clicked");
            decriptionArea.setText("");
            IssueBtnGrp.clearSelection();
       }
        else if (response == JOptionPane.YES_OPTION) {
        try {
            String query="insert into Response_Issue values(?,?,?,?,?,?)";
            //System.out.println(description);
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,issusename);
            ps.setString(2,id);
            ps.setString(3,"101914004");
            ps.setInt(4,0);
            ps.setString(5,description);
            ps.setInt(6,0);
            ps.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(ComplainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Issue Acknowledge");  
        IssueBtnGrp.clearSelection();
        decriptionArea.setText("");
        }
    }//GEN-LAST:event_submitBtnLabelMouseClicked

    private void crossBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossBtnLabelMouseClicked
       Student_Interface SI=new Student_Interface(id);
       this.setVisible(false);
       SI.setVisible(true);
        
    }//GEN-LAST:event_crossBtnLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup IssueBtnGrp;
    private javax.swing.JRadioButton cleanbtn;
    private javax.swing.JLabel crossBtnLabel;
    private javax.swing.JTextArea decriptionArea;
    private javax.swing.JRadioButton electricitybtn;
    private javax.swing.JRadioButton foodbtn;
    private javax.swing.JRadioButton internetbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton laundybtn;
    private javax.swing.JRadioButton seatcancelbtn;
    private javax.swing.JLabel submitBtnLabel;
    // End of variables declaration//GEN-END:variables
}
