
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class MonthlyBillAdd extends javax.swing.JFrame {

        Connection conn;
   Statement statement;
   ResultSet resultSet;
   ResultSetMetaData resultsetMetaData;
    public MonthlyBillAdd() {
        initComponents();
        OracleConnection OC=new OracleConnection();
        String[] stringArray = OC.connection();


        try{
           conn=DriverManager.getConnection(stringArray[0],stringArray[1],stringArray[2]);
            if(conn!=null)
            {
                
                System.out.println("Connection Sucessful in Monthly Bill Add Interface");
                statement=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            } 
        }catch(SQLException e){
            System.out.println("Connection failed");
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE );
        showData();
    }
    void showData()
    {
        DefaultTableModel model;
        model=(DefaultTableModel) monthlyBill.getModel(); 
        String query=String.format("select S_ID,S_Name from Student_Information where S_Status='1'");
            try {
                resultSet = statement.executeQuery(query);
                String stuid,name;
                while(resultSet.next())
                {
                       stuid=resultSet.getString("S_ID");
                       name=resultSet.getString("S_Name");
                       model.insertRow(model.getRowCount(),new Object[]{stuid,name,2200,false});
                }
            } catch (SQLException ex) {
                Logger.getLogger(MonthlyBillAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        monthlyBill = new javax.swing.JTable();
        addfinebtn = new javax.swing.JButton();
        addmonthlybillbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(874, 424));

        jPanel1.setLayout(null);

        monthlyBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Hall Bill", "Assign"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(monthlyBill);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 772, 279);

        addfinebtn.setText("Add To Fine");
        addfinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfinebtnActionPerformed(evt);
            }
        });
        jPanel1.add(addfinebtn);
        addfinebtn.setBounds(340, 380, 110, 23);

        addmonthlybillbtn.setText("Add Monthly Bill");
        addmonthlybillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmonthlybillbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addmonthlybillbtn);
        addmonthlybillbtn.setBounds(350, 30, 160, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addfinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfinebtnActionPerformed
        //String query=String.format("select count(*) as c from Bills");
    }//GEN-LAST:event_addfinebtnActionPerformed

    private void addmonthlybillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmonthlybillbtnActionPerformed
        
    }//GEN-LAST:event_addmonthlybillbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyBillAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyBillAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyBillAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyBillAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyBillAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfinebtn;
    private javax.swing.JButton addmonthlybillbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable monthlyBill;
    // End of variables declaration//GEN-END:variables
}
