
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class PasswordChangeInterface extends javax.swing.JFrame {
   Connection conn;
   Statement statement;
   ResultSet resultSet,resultSetPass,resultSet2;
   ResultSetMetaData resultsetMetaData;
   String Passed_id, newpass,mail,Confirmation_Code;
    public PasswordChangeInterface(String St_id) {
        initComponents();
        
        OracleConnection OC=new OracleConnection();
        String[] stringArray = OC.connection();
          try{
            conn=DriverManager.getConnection(stringArray[0],stringArray[1],stringArray[2]);
            if(conn!=null)
            {
                
                System.out.println("Connection Sucessful in PasswordChangeInterface");
                 statement=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            }
  
        }catch(SQLException e){
            System.out.println("Connection failed");
        }
      
        Passed_id=St_id;
        matchLabel.setVisible(false);
        curpasswarning.setVisible(false);
        passlengthlimit.setVisible(false);
        newpassText.setText("");
        confirmnewpassText.setText("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currpassText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        matchLabel = new javax.swing.JLabel();
        passchangebtn = new javax.swing.JLabel();
        passlengthlimit = new javax.swing.JLabel();
        curpasswarning = new javax.swing.JLabel();
        newpassText = new javax.swing.JPasswordField();
        confirmnewpassText = new javax.swing.JPasswordField();
        corssLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(27, 124, 161));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Password:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm New Password:");

        matchLabel.setForeground(new java.awt.Color(255, 0, 0));
        matchLabel.setText("*Not Matched with previos row");

        passchangebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/changeconfirm.png"))); // NOI18N
        passchangebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passchangebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passchangebtnMouseClicked(evt);
            }
        });

        passlengthlimit.setForeground(new java.awt.Color(204, 0, 51));
        passlengthlimit.setText("*Only 9 characters/digits");

        curpasswarning.setForeground(new java.awt.Color(204, 0, 0));
        curpasswarning.setText("*Current Password Wrong");

        newpassText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newpassTextFocusLost(evt);
            }
        });

        corssLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        corssLabel.setForeground(new java.awt.Color(255, 255, 255));
        corssLabel.setText("X");
        corssLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        corssLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corssLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(corssLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(newpassText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currpassText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(passlengthlimit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(confirmnewpassText, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(matchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(passchangebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(curpasswarning, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corssLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currpassText)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(newpassText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passlengthlimit)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(confirmnewpassText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matchLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(passchangebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(curpasswarning)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passchangebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passchangebtnMouseClicked
             
             curpasswarning.setVisible(false);
             String curpass=currpassText.getText();
            
             String confirmpass=confirmnewpassText.getText();
            
             if(Passed_id.charAt(0)=='2')
             {
                 String query=String.format("select S_Pass from student_information where S_ID='%s'",Passed_id);
                 try {
                   resultSet = statement.executeQuery(query);
                   resultSet.next();
                   String databasepass=resultSet.getString("S_Pass");
                   if(curpass.equals(databasepass))
                   {
                       
                            if(newpass.equals(confirmpass))
                            {
                                
                                    int response = JOptionPane.showConfirmDialog(null, "Are you Confirm?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                                    if (response == JOptionPane.YES_OPTION) 
                                    {
                                        
                                         //Generating Random Number
                                         Random rnd = new Random();
                                         int number = rnd.nextInt(999999);
                                         Confirmation_Code=String.format("%06d", number);
                                         
                                         //Sending Mainl
                                         String query3=String.format("select S_Email from student_information where S_ID='%s'",Passed_id);
                                         resultSet2 = statement.executeQuery(query3);
                                         resultSet2.next();
                                         mail=resultSet2.getString("S_Email");
                                         String message="Dear Student,\n"+"Your Password Change Confirmation Code is : "+Confirmation_Code;
                                         String sub="Password Change Confirmation Code"; 
                                         SendEmail SE=new SendEmail();
                                         SE.main(mail,sub,message);
                                         
                                          String givenConfirmationCOde = JOptionPane.showInputDialog(null, "Please enter your Confirmation Code.");
                                         if(givenConfirmationCOde.equals(Confirmation_Code))
                                         {
                                             String query2=String.format("update student_information set S_Pass='%s' where S_ID='%s'",confirmpass,Passed_id);
                                             resultSet = statement.executeQuery(query2);
                                             JFrame f=new JFrame();  
                                             JOptionPane.showMessageDialog(f,"Password Changed Successfully.");
                                             this.setVisible(false);
                                             LogIn LI=new LogIn();
                                             LI.setVisible(true);     
                                         }
                                         else
                                         {
                                             JFrame f=new JFrame();  
                                             JOptionPane.showMessageDialog(f,"Confirmation Code Doesn't Match.");
                                         }
                                    }
                                    else
                                    {
                                        currpassText.setText("");
                                        newpassText.setText("");
                                        confirmnewpassText.setText("");
                                         matchLabel.setVisible(false);
                                         curpasswarning.setVisible(false);
                                         passlengthlimit.setVisible(false);
                                    }
                            }
                            else
                            {
                                matchLabel.setVisible(true);
                            }
                            
                     }
                     else
                     {
                           curpasswarning.setVisible(true);
                     }
                   
                 }catch (SQLException ex) {
                  Logger.getLogger(PasswordChangeInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
             
             //employees
             else
             {
                 
                 String query=String.format("select Stuff_Pass from Stuff_Information where Stuff_ID='%s'",Passed_id);
                 try {
                   resultSet = statement.executeQuery(query);
                   resultSet.next();
                   String databasepass=resultSet.getString("Stuff_Pass");
                   if(curpass.equals(databasepass))
                   {
                       
                            if(newpass.equals(confirmpass))
                            {
                             int response = JOptionPane.showConfirmDialog(null, "Are you Confirm?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                             if (response == JOptionPane.YES_OPTION) 
                             {
                                  String query2=String.format("update Stuff_Information set Stuff_Pass='%s' where Stuff_ID='%s'",confirmpass,Passed_id);
                                  resultSet = statement.executeQuery(query2);
                                  this.setVisible(false);
                                  LogIn LI=new LogIn();
                                  LI.setVisible(true);
                             }
                             else
                             {
                                 currpassText.setText("");
                                 newpassText.setText("");
                                 confirmnewpassText.setText("");
                                  matchLabel.setVisible(false);
                                  curpasswarning.setVisible(false);
                                  passlengthlimit.setVisible(false);
                             }
                           }
                            else
                            {
                                matchLabel.setVisible(true);
                            }
                            
                       }
                       else
                       {
                           
                           curpasswarning.setVisible(true);
                       }
                   
                 }catch (SQLException ex) {
                  Logger.getLogger(PasswordChangeInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
    }//GEN-LAST:event_passchangebtnMouseClicked

    private void newpassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newpassTextFocusLost
        passlengthlimit.setVisible(false);
        newpass=newpassText.getText();
        if(newpass.length()>9)
        {
            passlengthlimit.setVisible(true);
        }
    }//GEN-LAST:event_newpassTextFocusLost

    private void corssLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corssLabelMouseClicked
       if(Passed_id.charAt(0)=='2')
        {
            Student_Interface SI=new Student_Interface(Passed_id);
            this.setVisible(false);
            SI.setVisible(true);
        }
       else
       {
           Stuff_Interface StI=new Stuff_Interface(Passed_id);
            this.setVisible(false);
            StI.setVisible(true);
           
       }
    }//GEN-LAST:event_corssLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PasswordChangeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmnewpassText;
    private javax.swing.JLabel corssLabel;
    private javax.swing.JLabel curpasswarning;
    private javax.swing.JTextField currpassText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JPasswordField newpassText;
    private javax.swing.JLabel passchangebtn;
    private javax.swing.JLabel passlengthlimit;
    // End of variables declaration//GEN-END:variables
}
