
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Stuff_Interface extends javax.swing.JFrame {

    Connection conn;
   Statement statement;
   ResultSet resultSet;
   ResultSetMetaData resultsetMetaData;
   
   String rank,id;
   
    public Stuff_Interface() {
        initComponents();
    }
    public Stuff_Interface(ResultSet res) {
        initComponents();
        OracleConnection OC=new OracleConnection();
        String[] stringArray = OC.connection();


        try{
           conn=DriverManager.getConnection(stringArray[0],stringArray[1],stringArray[2]);
            if(conn!=null)
            {
                
                System.out.println("Connection Sucessful in Stuff Interface");
                statement=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                resultSet=res;
   
            }
            
            
        }catch(SQLException e){
            System.out.println("Connection failed");
        }
        showInfo();
    }

    void showInfo(){
        
        try {
            resultSet.next();
            rank=resultSet.getString("Stuff_Rank");
            String name=resultSet.getString("Stuff_Name");
            id=resultSet.getString("Stuff_ID");
            

         //Counting rows of incoming contact table 
         String query2=String.format("select count(*) as c from Stuff_Information SI inner join Stuff_Contact SC on SI.Stuff_ID='%s' and SI.Stuff_ID=SC.Stuff_ID",id);
         resultSet = statement.executeQuery(query2);
         resultSet.next();
         int rowcount=resultSet.getInt("c");
         
         //For fetching info from Student_contact table
         
         String query3=String.format("select SC.Stuff_Phone_No from Stuff_Information SI inner join Stuff_Contact SC on SI.Stuff_ID='%s' and SI.Stuff_ID=SC.Stuff_ID",id);
          resultSet = statement.executeQuery(query3);
         
          int i=0;
          String phn1="",altphn="";
          while(resultSet.next())
          {
              if(i==0)
              {
                  phn1=resultSet.getString("Stuff_Phone_No");
              }
              else 
              {
                  altphn=resultSet.getString("Stuff_Phone_No");
              }
              i++;
          }
          rankfield.setText(rank);
          namefield.setText(name);
          idfield.setText(id);
          
          
           if(rowcount==1)
         {
             phnfield.setText(phn1);
             altphnfield.setVisible(false);
              altphnlabel.setVisible(false);
         }
         else
         {
             phnfield.setText(phn1);
             altphnfield.setText(altphn);
         }

        } catch (SQLException ex) {
            Logger.getLogger(Stuff_Interface.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phnlabel = new javax.swing.JLabel();
        ranktitle = new javax.swing.JLabel();
        nametitle = new javax.swing.JLabel();
        idtitle = new javax.swing.JLabel();
        assignbtn = new javax.swing.JButton();
        rankfield = new javax.swing.JLabel();
        namefield = new javax.swing.JLabel();
        idfield = new javax.swing.JLabel();
        phnfield = new javax.swing.JLabel();
        altphnlabel = new javax.swing.JLabel();
        altphnfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        phnlabel.setText("Phone Number:");
        jPanel1.add(phnlabel);
        phnlabel.setBounds(50, 210, 90, 30);

        ranktitle.setText("Rank :");
        jPanel1.add(ranktitle);
        ranktitle.setBounds(60, 90, 70, 30);

        nametitle.setText("Name");
        jPanel1.add(nametitle);
        nametitle.setBounds(60, 130, 70, 30);

        idtitle.setText("ID");
        jPanel1.add(idtitle);
        idtitle.setBounds(60, 170, 70, 30);

        assignbtn.setText("Assignment");
        assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbtnActionPerformed(evt);
            }
        });
        jPanel1.add(assignbtn);
        assignbtn.setBounds(230, 380, 170, 23);

        rankfield.setText("rank");
        jPanel1.add(rankfield);
        rankfield.setBounds(140, 100, 140, 14);

        namefield.setText("name");
        jPanel1.add(namefield);
        namefield.setBounds(130, 140, 200, 14);

        idfield.setText("id");
        jPanel1.add(idfield);
        idfield.setBounds(120, 180, 160, 14);

        phnfield.setText("phn");
        jPanel1.add(phnfield);
        phnfield.setBounds(140, 220, 200, 14);

        altphnlabel.setText("A:lternative Phn :");
        jPanel1.add(altphnlabel);
        altphnlabel.setBounds(40, 280, 90, 14);

        altphnfield.setText("alt phn");
        jPanel1.add(altphnfield);
        altphnfield.setBounds(140, 280, 210, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void assignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbtnActionPerformed
        if(rank.equals("Manager"))
        {
            ManagerInterface MI=new ManagerInterface(id);
            this.setVisible(false);
            MI.setVisible(true);
        }
        
        
    }//GEN-LAST:event_assignbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stuff_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altphnfield;
    private javax.swing.JLabel altphnlabel;
    private javax.swing.JButton assignbtn;
    private javax.swing.JLabel idfield;
    private javax.swing.JLabel idtitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namefield;
    private javax.swing.JLabel nametitle;
    private javax.swing.JLabel phnfield;
    private javax.swing.JLabel phnlabel;
    private javax.swing.JLabel rankfield;
    private javax.swing.JLabel ranktitle;
    // End of variables declaration//GEN-END:variables
}
