
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Stuff_Interface extends javax.swing.JFrame {

    Connection conn;
   Statement statement;
   ResultSet resultSet,resultSetPass;
   ResultSetMetaData resultsetMetaData;
   
   String rank,id,stuff_id_passes;
   
    public Stuff_Interface() {
        initComponents();
    }
    public Stuff_Interface(String Stuff_id) {
        initComponents();
        OracleConnection OC=new OracleConnection();
        String[] stringArray = OC.connection();


        try{
           conn=DriverManager.getConnection(stringArray[0],stringArray[1],stringArray[2]);
            if(conn!=null)
            {
                
                System.out.println("Connection Sucessful in Stuff Interface");
                statement=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                //resultSet=res;
                stuff_id_passes=Stuff_id;
   
            } 
        }catch(SQLException e){
            System.out.println("Connection failed");
        }
        showInfo();
    }

    void showInfo(){
        String query=String.format("select * from Stuff_Information where Stuff_ID='%s'",stuff_id_passes);
        try {
            resultSet = statement.executeQuery(query);
            resultSet.next();
            rank=resultSet.getString("Stuff_Rank");
            String name=resultSet.getString("Stuff_Name");
            id=resultSet.getString("Stuff_ID");
            

         //Counting rows of incoming contact table 
         String query2=String.format("select count(*) as c from Stuff_Information SI inner join Stuff_Contact SC on SI.Stuff_ID='%s' and SI.Stuff_ID=SC.Stuff_ID",id);
         resultSet = statement.executeQuery(query2);
         resultSet.next();
         int rowcount=resultSet.getInt("c");
         
         //For fetching info from Student_contact table
         
         String query3=String.format("select SC.Stuff_Phone_No from Stuff_Information SI inner join Stuff_Contact SC on SI.Stuff_ID='%s' and SI.Stuff_ID=SC.Stuff_ID",id);
          resultSet = statement.executeQuery(query3);
         
          int i=0;
          String phn1="",altphn="";
          while(resultSet.next())
          {
              if(i==0)
              {
                  phn1=resultSet.getString("Stuff_Phone_No");
              }
              else 
              {
                  altphn=resultSet.getString("Stuff_Phone_No");
              }
              i++;
          }
          rankfield.setText(rank);
          namefield.setText(name);
          idfield.setText(id);
          
          
           if(rowcount==1)
         {
             phnfield.setText(phn1);
             altphnfield.setVisible(false);
              altphnlabel.setVisible(false);
         }
         else
         {
             phnfield.setText(phn1);
             altphnfield.setText(altphn);
         }

        } catch (SQLException ex) {
            Logger.getLogger(Stuff_Interface.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phnlabel = new javax.swing.JLabel();
        ranktitle = new javax.swing.JLabel();
        nametitle = new javax.swing.JLabel();
        idtitle = new javax.swing.JLabel();
        rankfield = new javax.swing.JLabel();
        namefield = new javax.swing.JLabel();
        idfield = new javax.swing.JLabel();
        phnfield = new javax.swing.JLabel();
        altphnlabel = new javax.swing.JLabel();
        altphnfield = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AssignmentsBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        changepassbtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        phnlabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phnlabel.setText("Phone Number :");
        jPanel1.add(phnlabel);
        phnlabel.setBounds(40, 280, 140, 30);

        ranktitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ranktitle.setText("Rank :");
        jPanel1.add(ranktitle);
        ranktitle.setBounds(40, 120, 70, 30);

        nametitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nametitle.setText("Name :");
        jPanel1.add(nametitle);
        nametitle.setBounds(40, 170, 70, 30);

        idtitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idtitle.setText("ID :");
        jPanel1.add(idtitle);
        idtitle.setBounds(40, 220, 70, 30);

        rankfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rankfield.setText("rank");
        jPanel1.add(rankfield);
        rankfield.setBounds(220, 130, 140, 20);

        namefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namefield.setText("name");
        jPanel1.add(namefield);
        namefield.setBounds(220, 180, 200, 20);

        idfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idfield.setText("id");
        jPanel1.add(idfield);
        idfield.setBounds(220, 230, 160, 20);

        phnfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phnfield.setText("phn");
        jPanel1.add(phnfield);
        phnfield.setBounds(220, 290, 200, 20);

        altphnlabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        altphnlabel.setText("Alternative Phone  :");
        jPanel1.add(altphnlabel);
        altphnlabel.setBounds(40, 330, 170, 40);

        altphnfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        altphnfield.setText("alt phn");
        jPanel1.add(altphnfield);
        altphnfield.setBounds(220, 340, 210, 20);

        jPanel2.setBackground(new java.awt.Color(24, 44, 97));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 100);

        AssignmentsBtnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment.png"))); // NOI18N
        AssignmentsBtnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AssignmentsBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignmentsBtnLabelMouseClicked(evt);
            }
        });
        jPanel1.add(AssignmentsBtnLabel);
        AssignmentsBtnLabel.setBounds(230, 410, 130, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Your Assignments");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 390, 110, 20);

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logOutFromStudent.png"))); // NOI18N
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        jPanel1.add(logOut);
        logOut.setBounds(530, 440, 56, 70);

        changepassbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stuffpasschange.png"))); // NOI18N
        changepassbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepassbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepassbtnMouseClicked(evt);
            }
        });
        jPanel1.add(changepassbtn);
        changepassbtn.setBounds(30, 420, 70, 81);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Change Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 390, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AssignmentsBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentsBtnLabelMouseClicked
        if(rank.equals("Provost") || rank.equals("Deputy Provost") || rank.equals("Assistant Provost"))
        {
            Provost_interface PI=new Provost_interface(stuff_id_passes);
            this.setVisible(false);
            PI.setVisible(true);
        }
        
        else if(rank.equals("Manager"))
        {
            ManagerInterface MI=new ManagerInterface(stuff_id_passes);
            this.setVisible(false);
            MI.setVisible(true);
        }
        else if(rank.equals("Office Employee"))
        {
            Office_Employee_Interface OEI=new Office_Employee_Interface(stuff_id_passes);
            this.setVisible(false);
            OEI.setVisible(true);
        }
        
        else
        {
            AssignedWorkInterface AWI=new AssignedWorkInterface(stuff_id_passes);
            this.setVisible(false);
            AWI.setVisible(true);
        }
    }//GEN-LAST:event_AssignmentsBtnLabelMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        LogIn LI=new LogIn();
        this.setVisible(false);
        LI.setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void changepassbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtnMouseClicked
       PasswordChangeInterface PC=new PasswordChangeInterface(stuff_id_passes);
       this.setVisible(false);
       PC.setVisible(true);
    }//GEN-LAST:event_changepassbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stuff_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stuff_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssignmentsBtnLabel;
    private javax.swing.JLabel altphnfield;
    private javax.swing.JLabel altphnlabel;
    private javax.swing.JLabel changepassbtn;
    private javax.swing.JLabel idfield;
    private javax.swing.JLabel idtitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel namefield;
    private javax.swing.JLabel nametitle;
    private javax.swing.JLabel phnfield;
    private javax.swing.JLabel phnlabel;
    private javax.swing.JLabel rankfield;
    private javax.swing.JLabel ranktitle;
    // End of variables declaration//GEN-END:variables
}
